### ISSUE TITLE
Error when running compiled .jar

### ISSUE THREAD

**Issue by bkang97** [mashurex/java-pgo-bot#3]
[main] DEBUG c.ashurex.pokemon.PokebotProperties - Could not find properties file on the classpath.

I have a "pokebot.properties" file in the same directory as the .jar file. 

Can anybody help?

**Comment by mashurex** [comment]
That's a debug message that says it didn't find it on the classpath, which is where it looks first. It doesn't mean it can't run or it didn't find your properties file. 

Does it still read the properties you have set in your properties file?

**Comment by mashurex** [comment]
@bkang97 Does it seem to be reading your properties file?
