### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by KyleBoyer** [mashurex/java-pgo-bot#5]
Stack Trace

/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/BotMain.java:2: error: package POGOProtos.Enums does not exist
import POGOProtos.Enums.PokemonIdOuterClass;
                       ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/BotMain.java:5: error: package com.pokegoapi.exceptions does not exist
import com.pokegoapi.exceptions.RemoteServerException;
                               ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/PokemonBot.java:2: error: package POGOProtos.Enums.PokemonIdOuterClass does not exist
import POGOProtos.Enums.PokemonIdOuterClass.PokemonId;
                                           ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/PokemonBot.java:5: error: package com.pokegoapi.api does not exist
import com.pokegoapi.api.PokemonGo;
                        ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/PokemonBot.java:6: error: package com.pokegoapi.api.inventory does not exist
import com.pokegoapi.api.inventory.Inventories;
                                  ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/PokemonBot.java:7: error: package com.pokegoapi.api.map does not exist
import com.pokegoapi.api.map.Map;
                            ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/PokemonBot.java:8: error: package com.pokegoapi.api.map.pokemon does not exist
import com.pokegoapi.api.map.pokemon.CatchResult;
                                    ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/PokemonBot.java:9: error: package com.pokegoapi.api.map.pokemon does not exist
import com.pokegoapi.api.map.pokemon.CatchablePokemon;
                                    ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/BotOptions.java:3: error: package com.pokegoapi.auth does not exist
import com.pokegoapi.auth.CredentialProvider;
                         ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/BotOptions.java:4: error: package com.pokegoapi.auth does not exist
import com.pokegoapi.auth.GoogleUserCredentialProvider;
                         ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/BotOptions.java:5: error: package com.pokegoapi.auth does not exist
import com.pokegoapi.auth.PtcCredentialProvider;
                         ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/BotOptions.java:6: error: package com.pokegoapi.exceptions does not exist
import com.pokegoapi.exceptions.LoginFailedException;
                               ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/BotOptions.java:7: error: package com.pokegoapi.exceptions does not exist
import com.pokegoapi.exceptions.RemoteServerException;
                               ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/BotOptions.java:8: error: package com.pokegoapi.util does not exist
import com.pokegoapi.util.SystemTimeImpl;
                         ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/PokemonBot.java:33: error: cannot find symbol
    List<CatchablePokemon> getCatchablePokemon();
         ^
  symbol:   class CatchablePokemon
  location: interface PokemonBot
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/PokemonBot.java:34: error: cannot find symbol
    Inventories getInventory();
    ^
  symbol:   class Inventories
  location: interface PokemonBot
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/PokemonBot.java:35: error: cannot find symbol
    Map getMap();
    ^
  symbol:   class Map
  location: interface PokemonBot
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/PokemonBot.java:36: error: cannot find symbol
    PokemonGo getApi();
    ^
  symbol:   class PokemonGo
  location: interface PokemonBot
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/PokemonBot.java:39: error: cannot find symbol
    List<CatchResult> snipe(LatLng origin, LatLng destination, PokemonId pokemonId);
                                                               ^
  symbol:   class PokemonId
  location: interface PokemonBot
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/PokemonBot.java:39: error: cannot find symbol
    List<CatchResult> snipe(LatLng origin, LatLng destination, PokemonId pokemonId);
         ^
  symbol:   class CatchResult
  location: interface PokemonBot
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/BotOptions.java:158: error: cannot find symbol
    protected GoogleUserCredentialProvider cleanGoogleLogin(final OkHttpClient okHttpClient) throws LoginFailedException, RemoteServerException, IOException
              ^
  symbol:   class GoogleUserCredentialProvider
  location: class BotOptions
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/BotOptions.java:158: error: cannot find symbol
    protected GoogleUserCredentialProvider cleanGoogleLogin(final OkHttpClient okHttpClient) throws LoginFailedException, RemoteServerException, IOException
                                                                                                    ^
  symbol:   class LoginFailedException
  location: class BotOptions
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/BotOptions.java:158: error: cannot find symbol
    protected GoogleUserCredentialProvider cleanGoogleLogin(final OkHttpClient okHttpClient) throws LoginFailedException, RemoteServerException, IOException
                                                                                                                          ^
  symbol:   class RemoteServerException
  location: class BotOptions
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/BotOptions.java:172: error: cannot find symbol
    public CredentialProvider getCredentialProvider(final OkHttpClient okHttpClient)
           ^
  symbol:   class CredentialProvider
  location: class BotOptions
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/BotOptions.java:173: error: cannot find symbol
    throws LoginFailedException, RemoteServerException, IOException
           ^
  symbol:   class LoginFailedException
  location: class BotOptions
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/BotOptions.java:173: error: cannot find symbol
    throws LoginFailedException, RemoteServerException, IOException
                                 ^
  symbol:   class RemoteServerException
  location: class BotOptions
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/BotStep.java:4: error: package com.grum.geocalc does not exist
import com.grum.geocalc.EarthCalc;
                       ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/BotStep.java:5: error: package com.grum.geocalc does not exist
import com.grum.geocalc.Point;
                       ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/BotStep.java:19: error: cannot find symbol
    private final Point destination;
                  ^
  symbol:   class Point
  location: class BotStep
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/BotStep.java:20: error: cannot find symbol
    private final Point origin;
                  ^
  symbol:   class Point
  location: class BotStep
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/BotStep.java:93: error: cannot find symbol
    public Point getDestination()
           ^
  symbol:   class Point
  location: class BotStep
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/BotStep.java:98: error: cannot find symbol
    public Point getOrigin()
           ^
  symbol:   class Point
  location: class BotStep
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/SimplePokemonBot.java:2: error: package POGOProtos.Data.Player.PlayerStatsOuterClass does not exist
import POGOProtos.Data.Player.PlayerStatsOuterClass.PlayerStats;
                                                   ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/SimplePokemonBot.java:3: error: package POGOProtos.Enums does not exist
import POGOProtos.Enums.PokemonIdOuterClass;
                       ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/SimplePokemonBot.java:4: error: package POGOProtos.Networking.Responses does not exist
import POGOProtos.Networking.Responses.ReleasePokemonResponseOuterClass;
                                      ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/SimplePokemonBot.java:15: error: package com.pokegoapi.api does not exist
import com.pokegoapi.api.PokemonGo;
                        ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/SimplePokemonBot.java:16: error: package com.pokegoapi.api.gym does not exist
import com.pokegoapi.api.gym.Gym;
                            ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/SimplePokemonBot.java:17: error: package com.pokegoapi.api.inventory does not exist
import com.pokegoapi.api.inventory.CandyJar;
                                  ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/SimplePokemonBot.java:18: error: package com.pokegoapi.api.inventory does not exist
import com.pokegoapi.api.inventory.Inventories;
                                  ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/SimplePokemonBot.java:19: error: package com.pokegoapi.api.inventory does not exist
import com.pokegoapi.api.inventory.Stats;
                                  ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/SimplePokemonBot.java:20: error: package com.pokegoapi.api.map does not exist
import com.pokegoapi.api.map.Map;
                            ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/SimplePokemonBot.java:21: error: package com.pokegoapi.api.map.fort does not exist
import com.pokegoapi.api.map.fort.FortDetails;
                                 ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/SimplePokemonBot.java:22: error: package com.pokegoapi.api.map.fort does not exist
import com.pokegoapi.api.map.fort.Pokestop;
                                 ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/SimplePokemonBot.java:23: error: package com.pokegoapi.api.map.fort does not exist
import com.pokegoapi.api.map.fort.PokestopLootResult;
                                 ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/SimplePokemonBot.java:24: error: package com.pokegoapi.api.map.pokemon does not exist
import com.pokegoapi.api.map.pokemon.CatchResult;
                                    ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/SimplePokemonBot.java:25: error: package com.pokegoapi.api.map.pokemon does not exist
import com.pokegoapi.api.map.pokemon.CatchablePokemon;
                                    ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/SimplePokemonBot.java:26: error: package com.pokegoapi.api.map.pokemon does not exist
import com.pokegoapi.api.map.pokemon.EvolutionResult;
                                    ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/SimplePokemonBot.java:27: error: package com.pokegoapi.api.player does not exist
import com.pokegoapi.api.player.PlayerProfile;
                               ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/SimplePokemonBot.java:28: error: package com.pokegoapi.api.pokemon does not exist
import com.pokegoapi.api.pokemon.Pokemon;
                                ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/SimplePokemonBot.java:29: error: package com.pokegoapi.exceptions does not exist
import com.pokegoapi.exceptions.LoginFailedException;
                               ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/SimplePokemonBot.java:30: error: package com.pokegoapi.exceptions does not exist
import com.pokegoapi.exceptions.RemoteServerException;
                               ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/SimplePokemonBot.java:31: error: package com.pokegoapi.util does not exist
import com.pokegoapi.util.SystemTimeImpl;
                         ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/SimplePokemonBot.java:53: error: cannot find symbol
    private final PokemonGo api;
                  ^
  symbol:   class PokemonGo
  location: class SimplePokemonBot
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/SimplePokemonBot.java:99: error: cannot find symbol
    throws RemoteServerException, LoginFailedException, IOException
           ^
  symbol:   class RemoteServerException
  location: class SimplePokemonBot
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/SimplePokemonBot.java:99: error: cannot find symbol
    throws RemoteServerException, LoginFailedException, IOException
                                  ^
  symbol:   class LoginFailedException
  location: class SimplePokemonBot
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/SimplePokemonBot.java:121: error: cannot find symbol
        throws RemoteServerException, LoginFailedException, IOException
               ^
  symbol:   class RemoteServerException
  location: class SimplePokemonBot
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/SimplePokemonBot.java:121: error: cannot find symbol
        throws RemoteServerException, LoginFailedException, IOException
                                      ^
  symbol:   class LoginFailedException
  location: class SimplePokemonBot
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/SimplePokemonBot.java:160: error: package PokemonIdOuterClass does not exist
    public List<CatchResult> snipe(LatLng origin, LatLng destination, PokemonIdOuterClass.PokemonId pokemonId)
                                                                                         ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/SimplePokemonBot.java:160: error: cannot find symbol
    public List<CatchResult> snipe(LatLng origin, LatLng destination, PokemonIdOuterClass.PokemonId pokemonId)
                ^
  symbol:   class CatchResult
  location: class SimplePokemonBot
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/SimplePokemonBot.java:290: error: cannot find symbol
    public final Optional<Pokestop> getNearestPokestop()
                          ^
  symbol:   class Pokestop
  location: class SimplePokemonBot
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/SimplePokemonBot.java:398: error: cannot find symbol
    public List<Pokestop> getNearbyPokestops()
                ^
  symbol:   class Pokestop
  location: class SimplePokemonBot
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/SimplePokemonBot.java:415: error: cannot find symbol
    private PlayerStats getStats()
            ^
  symbol:   class PlayerStats
  location: class SimplePokemonBot
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/SimplePokemonBot.java:512: error: package ReleasePokemonResponseOuterClass.ReleasePokemonResponse does not exist
    private List<ReleasePokemonResponseOuterClass.ReleasePokemonResponse.Result> doTransfers()
                                                                        ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/SimplePokemonBot.java:522: error: cannot find symbol
    private List<EvolutionResult> doEvolutions()
                 ^
  symbol:   class EvolutionResult
  location: class SimplePokemonBot
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/SimplePokemonBot.java:545: error: cannot find symbol
    public Inventories getInventory()
           ^
  symbol:   class Inventories
  location: class SimplePokemonBot
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/SimplePokemonBot.java:579: error: cannot find symbol
    public List<CatchResult> catchNearbyPokemon()
                ^
  symbol:   class CatchResult
  location: class SimplePokemonBot
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/SimplePokemonBot.java:590: error: cannot find symbol
    public final Collection<Pokestop> getPokestops()
                            ^
  symbol:   class Pokestop
  location: class SimplePokemonBot
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/SimplePokemonBot.java:605: error: cannot find symbol
    public List<Gym> getGyms()
                ^
  symbol:   class Gym
  location: class SimplePokemonBot
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/SimplePokemonBot.java:660: error: cannot find symbol
    public List<CatchablePokemon> getCatchablePokemon()
                ^
  symbol:   class CatchablePokemon
  location: class SimplePokemonBot
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/SimplePokemonBot.java:682: error: cannot find symbol
    public synchronized List<PokestopLootResult> lootNearbyPokestops(boolean walkToStops)
                             ^
  symbol:   class PokestopLootResult
  location: class SimplePokemonBot
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/SimplePokemonBot.java:709: error: cannot find symbol
    public PokestopLootResult lootPokestop(Pokestop pokestop)
                                           ^
  symbol:   class Pokestop
  location: class SimplePokemonBot
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/SimplePokemonBot.java:709: error: cannot find symbol
    public PokestopLootResult lootPokestop(Pokestop pokestop)
           ^
  symbol:   class PokestopLootResult
  location: class SimplePokemonBot
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/SimplePokemonBot.java:720: error: cannot find symbol
    public synchronized final PokemonGo getApi()
                              ^
  symbol:   class PokemonGo
  location: class SimplePokemonBot
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/action/EggManager.java:2: error: package POGOProtos.Networking.Responses.UseItemEggIncubatorResponseOuterClass.UseItemEggIncubatorResponse does not exist
import POGOProtos.Networking.Responses.UseItemEggIncubatorResponseOuterClass.UseItemEggIncubatorResponse.Result;
                                                                                                        ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/action/EggManager.java:3: error: package com.pokegoapi.api.inventory does not exist
import com.pokegoapi.api.inventory.EggIncubator;
                                  ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/action/EggManager.java:4: error: package com.pokegoapi.api.inventory does not exist
import com.pokegoapi.api.inventory.Hatchery;
                                  ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/action/EggManager.java:5: error: package com.pokegoapi.api.inventory does not exist
import com.pokegoapi.api.inventory.Inventories;
                                  ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/action/EggManager.java:6: error: package com.pokegoapi.api.pokemon does not exist
import com.pokegoapi.api.pokemon.EggPokemon;
                                ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/action/EggManager.java:7: error: package com.pokegoapi.api.pokemon does not exist
import com.pokegoapi.api.pokemon.HatchedEgg;
                                ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/action/EggManager.java:24: error: cannot find symbol
    public static List<HatchedEgg> queryHatchedEggs(Hatchery hatchery)
                                                    ^
  symbol:   class Hatchery
  location: class EggManager
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/action/EggManager.java:24: error: cannot find symbol
    public static List<HatchedEgg> queryHatchedEggs(Hatchery hatchery)
                       ^
  symbol:   class HatchedEgg
  location: class EggManager
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/action/EggManager.java:47: error: cannot find symbol
    public static List<EggIncubator> getAvailableIncubators(Inventories inventory)
                                                            ^
  symbol:   class Inventories
  location: class EggManager
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/action/EggManager.java:47: error: cannot find symbol
    public static List<EggIncubator> getAvailableIncubators(Inventories inventory)
                       ^
  symbol:   class EggIncubator
  location: class EggManager
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/action/EggManager.java:67: error: cannot find symbol
    public static EggPokemon getAvailableEgg(Inventories inventory)
                                             ^
  symbol:   class Inventories
  location: class EggManager
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/action/EggManager.java:67: error: cannot find symbol
    public static EggPokemon getAvailableEgg(Inventories inventory)
                  ^
  symbol:   class EggPokemon
  location: class EggManager
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/action/EggManager.java:81: error: cannot find symbol
    public static List<EggIncubator> fillIncubators(Inventories inventory)
                                                    ^
  symbol:   class Inventories
  location: class EggManager
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/action/EggManager.java:81: error: cannot find symbol
    public static List<EggIncubator> fillIncubators(Inventories inventory)
                       ^
  symbol:   class EggIncubator
  location: class EggManager
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/action/EggManager.java:99: error: cannot find symbol
    public static Result hatchEgg(EggPokemon egg, EggIncubator incubator)
                                  ^
  symbol:   class EggPokemon
  location: class EggManager
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/action/EggManager.java:99: error: cannot find symbol
    public static Result hatchEgg(EggPokemon egg, EggIncubator incubator)
                                                  ^
  symbol:   class EggIncubator
  location: class EggManager
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/action/EggManager.java:99: error: cannot find symbol
    public static Result hatchEgg(EggPokemon egg, EggIncubator incubator)
                  ^
  symbol:   class Result
  location: class EggManager
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/action/GymFighter.java:2: error: package POGOProtos.Data.Battle does not exist
import POGOProtos.Data.Battle.BattlePokemonInfoOuterClass;
                             ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/action/GymFighter.java:3: error: package POGOProtos.Data does not exist
import POGOProtos.Data.PokemonDataOuterClass;
                      ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/action/GymFighter.java:4: error: package POGOProtos.Networking.Requests.Messages does not exist
import POGOProtos.Networking.Requests.Messages.StartGymBattleMessageOuterClass;
                                              ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/action/GymFighter.java:5: error: package POGOProtos.Networking.Requests does not exist
import POGOProtos.Networking.Requests.RequestTypeOuterClass;
                                     ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/action/GymFighter.java:6: error: package POGOProtos.Networking.Responses does not exist
import POGOProtos.Networking.Responses.AttackGymResponseOuterClass;
                                      ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/action/GymFighter.java:7: error: package POGOProtos.Networking.Responses does not exist
import POGOProtos.Networking.Responses.StartGymBattleResponseOuterClass;
                                      ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/action/GymFighter.java:8: error: package com.google.protobuf does not exist
import com.google.protobuf.InvalidProtocolBufferException;
                          ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/action/GymFighter.java:9: error: package com.pokegoapi.api does not exist
import com.pokegoapi.api.PokemonGo;
                        ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/action/GymFighter.java:10: error: package com.pokegoapi.api.gym does not exist
import com.pokegoapi.api.gym.Battle;
                            ^
/Users/Kyle/Desktop/java-pgo-bot/src/main/java/com/ashurex/pokemon/bot/action/GymFighter.java:11: error: package com.pokegoapi.api.gym does not exist
import com.pokegoapi.api.gym.Gym;
                            ^
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
100 errors
:compileJava FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':compileJava'.
  
  > Compilation failed; see the compiler error output for details.
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by mashurex** [comment]
Did you do `git submodule update --init --recursive` after checkout? It looks like the protobuf submodule didn't get pulled in from the PokeGOAPI-Java submodule.

**Comment by mashurex** [comment]
I just tested master with a clean checkout:

```
git clone https://github.com/mashurex/java-pgo-bot.git
cd java-pgo-bot
git submodule update --init --recursive
```

And it compiled just fine

**Comment by KyleBoyer** [comment]
I did indeed do so, but I bet my issue is that I downloaded the zip from the website instead of using git from the command line. I'll report back once I use git from the command line.

**Comment by KyleBoyer** [comment]
Kyles-MacBook-Pro-4:desktop Kyle$ git clone https://github.com/mashurex/java-pgo-bot.git
Cloning into 'java-pgo-bot'...
remote: Counting objects: 378, done.
remote: Compressing objects: 100% (167/167), done.
remote: Total 378 (delta 170), reused 314 (delta 111), pack-reused 0
Receiving objects: 100% (378/378), 76.34 KiB | 0 bytes/s, done.
Resolving deltas: 100% (170/170), done.
Checking connectivity... done.
Kyles-MacBook-Pro-4:desktop Kyle$ cd java-pgo-bot
Kyles-MacBook-Pro-4:java-pgo-bot Kyle$ git submodule update --init --recursive
Submodule 'submodules/PokeGOAPI-Java' (https://github.com/Grover-c13/PokeGOAPI-Java) registered for path 'submodules/PokeGOAPI-Java'
Submodule 'submodules/geocalc' (https://github.com/grumlimited/geocalc.git) registered for path 'submodules/geocalc'
Cloning into 'submodules/PokeGOAPI-Java'...
remote: Counting objects: 4591, done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 4591 (delta 26), reused 0 (delta 0), pack-reused 4528
Receiving objects: 100% (4591/4591), 8.88 MiB | 360.00 KiB/s, done.
Resolving deltas: 100% (2139/2139), done.
Checking connectivity... done.
Submodule path 'submodules/PokeGOAPI-Java': checked out 'cca2a1cf0bdc2ba18d6863f91edd156d463273cc'
Submodule 'library/src/resources/protobuf' (https://github.com/AeonLucid/POGOProtos.git) registered for path 'library/src/resources/protobuf'
Cloning into 'library/src/resources/protobuf'...
remote: Counting objects: 1853, done.
remote: Compressing objects: 100% (148/148), done.
remote: Total 1853 (delta 54), reused 0 (delta 0), pack-reused 1705
Receiving objects: 100% (1853/1853), 265.27 KiB | 154.00 KiB/s, done.
Resolving deltas: 100% (932/932), done.
Checking connectivity... done.
Submodule path 'submodules/PokeGOAPI-Java/library/src/resources/protobuf': checked out '333e54707ca221324c6b9eedb6a7bc2fcae02270'
Cloning into 'submodules/geocalc'...
remote: Counting objects: 384, done.
remote: Total 384 (delta 0), reused 0 (delta 0), pack-reused 384
Receiving objects: 100% (384/384), 61.23 KiB | 0 bytes/s, done.
Resolving deltas: 100% (121/121), done.
Checking connectivity... done.
Submodule path 'submodules/geocalc': checked out '772f3c23f1dbfdc356aba84dd8108374f210f04f'
Kyles-MacBook-Pro-4:java-pgo-bot Kyle$ gradle build
You are using Gradle 2.8:  This version of the protobuf plugin works with Gradle version 2.12+

FAILURE: Build failed with an exception.
- Where:
  Build file '/Users/Kyle/Desktop/java-pgo-bot/submodules/PokeGOAPI-Java/library/build.gradle' line: 13
- What went wrong:
  A problem occurred evaluating project ':PokeGOAPI-Java'.
  
  > Failed to apply plugin [id 'com.google.protobuf']
  > Could not create an instance of type com.google.protobuf.gradle.ProtobufSourceDirectorySet_Decorated.
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 6.698 secs
